/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Card: typeof import('./src/components/Card.vue')['default']
    CardForm: typeof import('./src/components/CardForm.vue')['default']
    DashboardCartaoCredito: typeof import('./src/components/dashboard/cartao-credito/DashboardCartaoCredito.vue')['default']
    DashboardContas: typeof import('./src/components/dashboard/contas/DashboardContas.vue')['default']
    DespesaCategory: typeof import('./src/components/dashboard/contas/components/DespesaCategory.vue')['default']
    GastoAnualCartao: typeof import('./src/components/dashboard/cartao-credito/components/GastoAnualCartao.vue')['default']
    GastoCategoriaCartaoMensal: typeof import('./src/components/dashboard/cartao-credito/components/GastoCategoriaCartaoMensal.vue')['default']
    GastoCategoriaMensal: typeof import('./src/components/dashboard/cartao-credito/components/GastoCategoriaMensal.vue')['default']
    GastoMensalCartao: typeof import('./src/components/dashboard/cartao-credito/components/GastoMensalCartao.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MetricCards: typeof import('./src/components/dashboard/contas/components/MetricCards.vue')['default']
    MetricsCards: typeof import('./src/components/dashboard/cartao-credito/components/MetricsCards.vue')['default']
    MetricsCardsCredit: typeof import('./src/components/dashboard/cartao-credito/components/MetricsCardsCredit.vue')['default']
    PayReceiveComparison: typeof import('./src/components/dashboard/contas/components/PayReceiveComparison.vue')['default']
    ReceitaCategory: typeof import('./src/components/dashboard/contas/components/ReceitaCategory.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SaldoAnual: typeof import('./src/components/dashboard/contas/components/SaldoAnual.vue')['default']
  }
}
